export const testD: any = [
  {
    id: 9,
    name: '阿里云23',
    pid: 2,
    type: 2,
    typeName: '部门',
    hasChild: 2,
    hasChildName: '否',
    sort: 7,
    createUser: 1,
    createUserName: '管理员',
    createTime: '2020-05-17 10:54:49',
    updateUser: 1,
    updateUserName: '管理员',
    updateTime: '2021-01-27 15:28:04',
  },
  {
    id: 8,
    name: '阿里小企业业务',
    pid: 2,
    type: 2,
    typeName: '部门',
    hasChild: 2,
    hasChildName: '否',
    sort: 6,
    createUser: 1,
    createUserName: '管理员',
    createTime: '2020-05-17 10:54:37',
    updateUser: 0,
    updateUserName: null,
    updateTime: null,
  },
  {
    id: 7,
    name: '阿里国际业务',
    pid: 2,
    type: 2,
    typeName: '部门',
    hasChild: 2,
    hasChildName: '否',
    sort: 5,
    createUser: 1,
    createUserName: '管理员',
    createTime: '2020-05-17 10:54:15',
    updateUser: 0,
    updateUserName: null,
    updateTime: null,
  },
  {
    id: 6,
    name: '聚划算',
    pid: 2,
    type: 2,
    typeName: '部门',
    hasChild: 2,
    hasChildName: '否',
    sort: 4,
    createUser: 1,
    createUserName: '管理员',
    createTime: '2020-05-17 10:54:01',
    updateUser: 0,
    updateUserName: null,
    updateTime: null,
  },
  {
    id: 5,
    name: '天猫',
    pid: 2,
    type: 2,
    typeName: '部门',
    hasChild: 2,
    hasChildName: '否',
    sort: 3,
    createUser: 1,
    createUserName: '管理员',
    createTime: '2020-05-17 10:53:49',
    updateUser: 0,
    updateUserName: null,
    updateTime: null,
  },
  {
    id: 4,
    name: '一淘',
    pid: 2,
    type: 2,
    typeName: '部门',
    hasChild: 2,
    hasChildName: '否',
    sort: 2,
    createUser: 1,
    createUserName: '管理员',
    createTime: '2020-05-17 10:53:39',
    updateUser: 0,
    updateUserName: null,
    updateTime: null,
  },
  {
    id: 3,
    name: '淘宝',
    pid: 2,
    type: 2,
    typeName: '部门',
    hasChild: 2,
    hasChildName: '否',
    sort: 1,
    createUser: 1,
    createUserName: '管理员',
    createTime: '2020-05-17 10:53:26',
    updateUser: 1,
    updateUserName: '管理员',
    updateTime: '2020-05-17 10:54:57',
  },
  {
    id: 2,
    name: '阿里巴巴事业群',
    pid: 1,
    type: 2,
    typeName: '部门',
    hasChild: 1,
    hasChildName: '是',
    sort: 1,
    createUser: 1,
    createUserName: '管理员',
    createTime: '2020-05-17 10:53:04',
    updateUser: 1,
    updateUserName: '管理员',
    updateTime: '2021-01-27 15:05:07',
  },
  {
    id: 1,
    name: '阿里巴巴网络科技有限公司',
    pid: 0,
    type: 1,
    typeName: '公司',
    hasChild: 1,
    hasChildName: '是',
    sort: 1,
    createUser: 1,
    createUserName: '管理员',
    createTime: '2020-05-17 10:52:48',
    updateUser: 1,
    updateUserName: '管理员',
    updateTime: '2021-01-27 15:28:54',
  },
];
